<center> <h1> Google Maps API </h> </center> 
<center> <h2> Homework 1 </h> </center> 
<center> <h3> Data Preprocessing </h> </center>

A. Use the [*Nearby Seach*](https://developers.google.com/places/web-service/search) Method to find all the restaurant near to the UPY (20.988459, -89.736768) around 2km. In order to fulfill this item you need to:
* Create a *search_nearby_places* function with the appropiate parameters. It must return a JSON with the results. Places must be ranked by distance.
* Create a table with the following columns: Name, Place Id, Rating, Place Types, Total of User Ratings.

In [1]:
import time
import json
import requests
import pandas as pd
import googlemaps
gmaps = googlemaps.Client(key = 'Your API KEY')

In [2]:
#AIzaSyCUUvP-TGxfZ0nqMOEcs7PmpET_ZeyeYpk
def NearbySeach(key, location, radius,type1):
    """
    Function to obtain data of places which are near to a specific location using request and json

    Args:
        key: our API key which will give us the access of the Google's API
        location: Where is the place that we want to know as LAT/LONG in string separated by commas
        radius: A radius in meters to know how near are the places
        type1:
        
    Returns:

     A dictionary with the places which are near in the given radius


    """    
    

    endpoint_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'
    params = {
        'key' : key,
        'location' : location,
        'radius' : radius,
        'type' : type1
    }
    
    res = requests.get(endpoint_url, params= params)
    results = res.content
    return results

In [3]:
upy = NearbySeach('Your API KEY', '20.988459,-89.736768', 2000, 'all')
upy = json.loads(upy)
len(upy['results'])

20

In [4]:
dataFrame = pd.read_json(json.dumps(upy['results']), orient='records')
newData = pd.DataFrame()
newData['name'] = dataFrame['name']
newData['Place Id'] = dataFrame['id']
newData['Rating'] = dataFrame['rating']
newData['Place Types'] = dataFrame['types']
newData['Total of User Ratings'] = dataFrame['user_ratings_total']
newData

,name,Place Id,Rating,Place Types,Total of User Ratings
0,Chalmuch,a2c08c98d9130840e7e2a93077a5926e7058b443,NaN,"[locality, political]",NaN
1,Universidad Politécnica de Yucatán,72302ba843a3993183cad61f01b240e8456a5c8f,4.4,"[university, point_of_interest, establishment]",37.0
2,Corporativo Magav Sureste SA de CV,747f78b29efa28d1c9a89170ee3ce568d08426e8,4.3,"[point_of_interest, establishment]",9.0
3,Oxxo 50Zuc Tamarindo,c933be62e6d698c2cf527200bfab52956297b91d,NaN,"[atm, finance, point_of_interest, establishment]",NaN
4,ENES UNAM CAMPUS MÉRIDA,2c881b1e862f83c7732be203632024e4cd1561d9,5.0,"[school, point_of_interest, establishment]",2.0
5,ENES Mérida,59b4b383dffbc081365211626c0b314f7c0edbac,NaN,"[university, point_of_interest, establishment]",NaN
6,ENES unidad Mérida UNAM - Campus Yucatán,82ebc14d5d26c4b043aba7e484ab00f757113ff9,NaN,"[school, point_of_interest, establishment]",NaN
7,Lavanderia MI TERESITA,46336d0c35ed9890a56e4141b509aed416dba3f9,5.0,"[laundry, point_of_interest, establishment]",3.0
8,Tanis NaiL's,cb962bc723f42ccd301925edb0be482292274792,NaN,"[point_of_interest, establishment]",NaN
9,PLANTA DE TRATAMIENTO DE AGUAS RESIDUALES,1ac141c570284466de78604d1b9bae92be9d4c7c,NaN,"[point_of_interest, establishment]",NaN
10,Consultorio Dental Lecks-dent,b2ff6b070da472d8b6675ef4c6c4c50df1a985bf,5.0,"[dentist, health, point_of_interest, establish...",1.0
11,Llantera Real,cf0bae9746fa7c4d411b648554caeb59a5ed3737,NaN,"[point_of_interest, establishment]",NaN
12,Akkaax,887368e5628b9866efe405cea23747c25ae6291c,NaN,"[school, point_of_interest, establishment]",NaN
13,Glorieta Colibrí,98e5dcb47bc45ef0b00a8f9e8367cca5531a9d68,NaN,"[park, point_of_interest, establishment]",NaN
14,Consultorio Dental Leckdent,1fb37948c30b6775c528f60660f6407c1d936930,NaN,"[doctor, health, point_of_interest, establishm...",NaN
15,Consultorio Dental Leckdent,71d9a65dc3eae91a6218d98d04dc0cfc5088a0c1,NaN,"[doctor, health, point_of_interest, establishm...",NaN
16,Fractionation Live Alegre,41be875139671f6b8c18f60b7f6052f341a383be,4.0,"[general_contractor, point_of_interest, establ...",38.0
17,Grupo Alto Desarrolladores,dd58c298cbd248e4e9af9e79688a61f374d46a34,3.9,"[point_of_interest, establishment]",14.0
18,Glorieta Del Cristiano,451e66a773c0096bd27e0440dfa43a354095b473,4.0,"[park, point_of_interest, establishment]",42.0
19,La Glorieta (Cocina y Pizzería),51215063e260371f31be9c48b4b35f276677d8df,4.1,"[restaurant, food, point_of_interest, establis...",14.0

B. Create a function to Find the Place Id given Place Name (String) and Location (Lat/Lont Tuple).

In [5]:
def idPlace(name, key, location):
    """
    Function to obtain the ID of a place given the name and the location

    Args:
        name: The name of the place
        key: Our API key to access to the Google's API
        location: Where is the place that we want to know as LAT/LONG in string separated by commas

    Returns:
        
     A dictionary with the ID of the place
     

    """
    
    endpoint_url = 'https://maps.googleapis.com/maps/api/place/findplacefromtext/json?'
    locationbias = 'circle:100@'+ location
    params = {
        'input' : name,
        'key' : key,
        'inputtype' : 'textquery',
        'locationbias' : locationbias,
    }
    
    res = requests.get(endpoint_url, params = params)
    results = res.content
    results = json.loads(results)
    return results

C. Find the Place ID of the following places using your functions:
* McCarthy's Irish Pub - Caucel
* Starbucks Montejo
* Los Trompos Circuito

In [6]:
mcCarthys = idPlace('mcCarthys','Your API KEY', '21.000144,-89.682604')
starbucks = idPlace('starbucks','Your API KEY', '20.984712, -89.618091')
trompos = idPlace('trompos','Your API KEY', '20.998915, -89.617438')

D. Use the [*Place Details*](https://developers.google.com/places/web-service/details#PlaceDetailsResults) Method to find the Reviews of a Place in English and Spanish. In order to fulfill this item you need to:
* Create a *find_reviews* function with the appropiate parameters. It must return a JSON with the results. 
* Create a table with the following columns: Author Name, Language, Rating, Text, Time.

In [7]:
def find_request(key, iD, language):
    """
    Function to obtaion the reviews of a Place in a specific language

    Args:
        key: Our API key to access to the Google's API
        iD: The ID of the place
        language: The language of the reviews

    Returns:
        
     A dictionary with the reviews in the given language
     

    """

    endpoint_url = 'https://maps.googleapis.com/maps/api/place/details/json?'
    params = {
        'key' : key,
        'place_id' : iD,
        'language' : language
    }
    
    res = requests.get(endpoint_url, params = params)
    results = res.content
    results = json.loads(results)
    return results

# SPANISH

In [8]:
mcCarthysEs = find_request('Your API KEY',mcCarthys['candidates'][0]['place_id'], 'es')
mcCarthysEs = pd.read_json(json.dumps(mcCarthysEs['result']['reviews']), orient='records')

starbucksEs = find_request('Your API KEY',starbucks['candidates'][0]['place_id'], 'es')
starbucksEs = pd.read_json(json.dumps(starbucksEs['result']['reviews']), orient='records')

tromposEs = find_request('Your API KEY',trompos['candidates'][0]['place_id'], 'es')
tromposEs = pd.read_json(json.dumps(tromposEs['result']['reviews']), orient='records')

# ENGLISH

In [9]:
mcCarthysEn = find_request('Your API KEY',mcCarthys['candidates'][0]['place_id'], 'en')
mcCarthysEn = pd.read_json(json.dumps(mcCarthysEn['result']['reviews']), orient='records')

starbucksEn = find_request('Your API KEY',starbucks['candidates'][0]['place_id'], 'en')
starbucksEn = pd.read_json(json.dumps(starbucksEn['result']['reviews']), orient='records')

tromposEn = find_request('Your API KEY',trompos['candidates'][0]['place_id'], 'en')
tromposEn = pd.read_json(json.dumps(tromposEn['result']['reviews']), orient='records')

In [10]:
frames = [mcCarthysEs, mcCarthysEn, tromposEs, tromposEn, starbucksEn, starbucksEs]
df_keys = pd.concat(frames, keys=['mcCarthysEs','mcCarthysEn', 'tromposEs', 'tromposEn','starbucksEn', 'starbucksEs'])
df_keys.drop(["author_url", "profile_photo_url","relative_time_description"], axis=1, inplace=True)
df_keys

                               author_name language  rating  \
mcCarthysEs 0          Gustavo Balan smith       es       5
            1             Fernando Estrada       es       4
            2                   Ian Vazsan       es       5
            3          Diseñosalon Xgarcia       es       4
            4          Alejandra  Casanova       es       4
mcCarthysEn 0              David Guillermo       en       3
            1                      Patrick       en       5
            2                        Islas       en       5
            3                 Toni Aguilar       en       5
            4                monica ravell       en       5
tromposEs   0                Jesus Roblero       es       4
            1                Gerardo Canto       es       5
            2              Victoria Carmin       es       3
            3                   Jorge Ruiz       es       5
            4                  Jc Guerrero       es       5
tromposEn   0             Patricia Ramirez       en       5
            1                 andres dueck       en       5
            2               Robert Hamblin       en       5
            3                  Cris Martin       en       5
            4                Christi Foist       en       5
starbucksEn 0              Brandy Campbell       en       5
            1                          J T       en       4
            2                     Amy King       en       4
            3                 James Wilson       en       3
            4                     Carlos G       en       1
starbucksEs 0  Pedro Alberto Herrera Perez       es       2
            1                     Kat Tosa       es       5
            2                ricardo nuñez       es       5
            3            Daniel Villalobos       es       4
            4              Josue Cervantes       es       4

                                                            text        time
mcCarthysEs 0  Buen lugar super amables todos buen lugar para...  1569553044
            1  Fuimos viernes en la noche. Buena banda tocand...  1564530272
            2                   La promo de alitas está de lujo.  1568990169
            3               Ambiente tranquilo a la hora que fui  1569195706
            4  Buen lugar para escuchar buen rock. De domingo...  1566197539
mcCarthysEn 0  They need person to regulate the sound inside ...  1566612760
            1  One of the best pubs around.\nGreat service, g...  1518688093
            2  I love this place, one of the best places to d...  1522860496
            3  Rockers, music lovers in general will enjoy th...  1516852970
            4                 Great place to listen to good rock  1531876412
tromposEs   0  Fuimos en grupo con compañeros de trabajo (apr...  1567777349
            1  Ambiente familiar y muy buena comida. Sugiero ...  1569546192
            2  Buena atención por parte del mesero, solo falt...  1564412760
            3  Muy rico todo como siempre, los juegos y la at...  1568460826
            4  Las pizzas están deliciosas, la masa es única ...  1563213141
tromposEn   0                          Best tacos I've ever had!  1567825418
            1  Food was extremely good!! Worse thing was I ov...  1569549855
            2  Friendly staff. Clean bathrooms. Have the Alam...  1561151931
            3       Great mexican food frijoles charos are great  1560024294
            4        Great, affordable tacos and friendly staff.  1563161376
starbucksEn 0  They are always so fast and very polite. I'm a...  1558744858
            1  Lovely place. Good service. I have one request...  1543268696
            2          Lots of space in this two story starbucks  1560620959
            3  I am Canadian and rarely visit Starbucks anywh...  1544219879
            4  This Starbucks S..CKS...!!!!... the worst coff...  1547604761
starbucksEs 0  Pésima atención. Excelente calidad de comida y...  1569002874
            1  Excelente lugar para colaborar y disfrutar de ...  1568776228
            2  Siempre amables muy serviciales con los client...  1569074473
            3                 Muy agradable lugar, mucho espacio  1567700603
            4  aveces un poco lentos y distraídos. Aire un po...  1566315318

E. Find similar places to Los Trompos Circuito. Rank them by its "Prominence". In order to fulfill this item you need to:
* Create a *find_similar* function with the appropiate parameters. It must return a JSON with the results.
* Create a table with the following columns: Place Name, Plaece Id, Rating, Total of Use Ratings.

In [11]:
def find_similar(key, location, radius,type1):
    """
    Function to obtain similar places of a given place

    Args:
        key: Our API key to access to the Google's API
        location: Where is the place that we want to know as LAT/LONG in string separated by commas
        radius: The radius of how long we want to cover
        type1: the type of place that we want to search (restaurant, bar, etc)

    Returns:
        
     A dictionary with the places which are similar
     

    """
    endpoint_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'
    params = {
        'key' : key,
        'location' : location,
        'radius' : radius,
        'type' : type1,
        'rankby' : 'prominence'
    }
    
    res = requests.get(endpoint_url, params= params)
    results = res.content
    results = json.loads(results)
    return results

In [12]:
similarTrompos = find_similar('Your API KEY', '20.999070, -89.617521', 2000,'restaurant')
similarTrompos = pd.read_json(json.dumps(similarTrompos['results']), orient='records')
similarTrompos.drop(["geometry","id", "icon", "opening_hours", "photos","types", "plus_code", "price_level", "reference","vicinity","scope"], axis=1, inplace=True)
similarTrompos.head()

,name,place_id,rating,user_ratings_total
0,Alcatraz,ChIJEWeemsl2Vo8R-1OGMd37lV0,NaN,NaN
1,La Parrilla,ChIJLdBR77F2Vo8RuHJbN6nF_ng,4.1,1181.0
2,Pollo Brujo Reforma,ChIJw61ohuJzVo8RRd1vlJDdiBI,4.4,229.0
3,El Guacamayo Restaurante Bar,ChIJS3UJ0FBxVo8RFjqPj7X_db0,3.6,5.0
4,Eladio's,ChIJ9yoFwm5xVo8Rppx5yDFu_oQ,4.5,2058.0

F. Complete all the above tasks but using the Python [GoogleMaps](https://github.com/googlemaps/google-maps-services-python) Library. [Here](https://googlemaps.github.io/google-maps-services-python/docs/#module-googlemaps) you can find the documentation.

# PROBLEM A

In [13]:

places = gmaps.places_nearby(location = '20.988459, -89.736768', radius = 2000, type = 'all', open_now = False)
restaurants_UPY = pd.read_json(json.dumps(places['results']), orient = 'columns')
restaurants_UPY = restaurants_UPY[['name','place_id','rating','types','user_ratings_total']]
restaurants_UPY

,name,place_id,rating,types,user_ratings_total
0,Chalmuch,ChIJKWfQHe0MVo8RzMu0WTpAAIU,NaN,"[locality, political]",NaN
1,Universidad Politécnica de Yucatán,ChIJ37xdwYcMVo8R3BSORZutD64,4.4,"[university, point_of_interest, establishment]",37.0
2,Corporativo Magav Sureste SA de CV,ChIJd0aXMJ4MVo8Rc-Cgg1_LFFw,4.3,"[point_of_interest, establishment]",9.0
3,Oxxo 50Zuc Tamarindo,ChIJVyk_oOgNVo8RYPVZht5EIzo,NaN,"[atm, finance, point_of_interest, establishment]",NaN
4,ENES UNAM CAMPUS MÉRIDA,ChIJNQe7socMVo8RNlMICaiTOnw,5.0,"[school, point_of_interest, establishment]",2.0
5,ENES Mérida,ChIJWZhnnDINVo8RYlu_8cdN91M,NaN,"[university, point_of_interest, establishment]",NaN
6,ENES unidad Mérida UNAM - Campus Yucatán,ChIJvwqXp6ENVo8R88xRb2PYivU,NaN,"[school, point_of_interest, establishment]",NaN
7,Lavanderia MI TERESITA,ChIJnzYNMZsMVo8RRJBJWl1rDhk,5.0,"[laundry, point_of_interest, establishment]",3.0
8,Tanis NaiL's,ChIJedBbF1UNVo8RqjIL3Yuodjo,NaN,"[point_of_interest, establishment]",NaN
9,PLANTA DE TRATAMIENTO DE AGUAS RESIDUALES,ChIJqxl0bC0NVo8RhZSJdfMI-44,NaN,"[point_of_interest, establishment]",NaN
10,Consultorio Dental Lecks-dent,ChIJ9VDYBTYNVo8RmAg4UY6c3MU,5.0,"[dentist, health, point_of_interest, establish...",1.0
11,Llantera Real,ChIJyTSiw_cNVo8R4tOomJ-6brM,NaN,"[point_of_interest, establishment]",NaN
12,Akkaax,ChIJQziHc2UMVo8RwvNImxJPL0I,NaN,"[school, point_of_interest, establishment]",NaN
13,Glorieta Colibrí,ChIJ4dzRwIcNVo8RcIkh52CxMj8,NaN,"[park, point_of_interest, establishment]",NaN
14,Consultorio Dental Leckdent,ChIJsePs_lANVo8RMWgPJyzUKZs,NaN,"[doctor, health, point_of_interest, establishm...",NaN
15,Consultorio Dental Leckdent,ChIJeakScLYNVo8RGF075gnVHmg,NaN,"[doctor, health, point_of_interest, establishm...",NaN
16,Fractionation Live Alegre,ChIJB5TwvJsMVo8RYzpMnH5aQ0w,4.0,"[general_contractor, point_of_interest, establ...",38.0
17,Grupo Alto Desarrolladores,ChIJK3HXv5sMVo8RyY1o-BZ-1Qw,3.9,"[point_of_interest, establishment]",14.0
18,Glorieta Del Cristiano,ChIJayQsXJwMVo8Rt-3616DrFOg,4.0,"[park, point_of_interest, establishment]",42.0
19,La Glorieta (Cocina y Pizzería),ChIJC9i7XEsNVo8Ro2-sdS45rBg,4.1,"[restaurant, food, point_of_interest, establis...",14.0

# PROBLEM C

In [14]:
place_id_McCarthys = gmaps.find_place(input = "McCarthy's Irish Pub - Caucel", input_type = 'textquery', location_bias = 'point:21.000164, -89.682577')
place_id_Starbucks = gmaps.find_place(input = "Starbucks Montejo", input_type = 'textquery', location_bias = 'point:20.986084, -89.617962')
place_id_Trompos = gmaps.find_place(input = "Los Trompos Circuito", input_type = 'textquery', location_bias = 'point:21.002306, -89.616801')

# print the place ID.
print("McCarthy's Irish Pub - Caucel place ID:", place_id_McCarthys['candidates'][0]['place_id'])
print("Starbucks Montejo place ID:", place_id_Starbucks['candidates'][0]['place_id'])
print("Los Trompos Circuito place ID:", place_id_Trompos['candidates'][0]['place_id'])

McCarthy's Irish Pub - Caucel place ID: ChIJJyKKOKB0Vo8RCQcxkUw6hp8
Starbucks Montejo place ID: ChIJaUUfylFxVo8RgEGjoansPbc
Los Trompos Circuito place ID: ChIJpVKXOq12Vo8RK4bUWILT9dI

# PROBLEM D

In [18]:
reviewsEs = gmaps.place(place_id='ChIJJyKKOKB0Vo8RCQcxkUw6hp8', language='es')
reviewsEs=pd.read_json(json.dumps(reviewsEs['result']['reviews']), orient='records')

reviewsEn= gmaps.place(place_id='ChIJJyKKOKB0Vo8RCQcxkUw6hp8', language='en')
reviewsEn=pd.read_json(json.dumps(reviewsEn['result']['reviews']), orient='records')

frames = [reviewsEs, reviewsEn]
df_k = pd.concat(frames, keys=['mcCarthysEs','mcCarthysEn', 'tromposEs', 'tromposEn','starbucksEn', 'starbucksEs'])
df_k.drop(["author_url", "profile_photo_url","relative_time_description"], axis=1, inplace=True)
df_k

                       author_name language  rating  \
mcCarthysEs 0  Gustavo Balan smith       es       5
            1     Fernando Estrada       es       4
            2           Ian Vazsan       es       5
            3  Diseñosalon Xgarcia       es       4
            4  Alejandra  Casanova       es       4
mcCarthysEn 0      David Guillermo       en       3
            1              Patrick       en       5
            2                Islas       en       5
            3         Toni Aguilar       en       5
            4        monica ravell       en       5

                                                            text        time
mcCarthysEs 0  Buen lugar super amables todos buen lugar para...  1569553044
            1  Fuimos viernes en la noche. Buena banda tocand...  1564530272
            2                   La promo de alitas está de lujo.  1568990169
            3               Ambiente tranquilo a la hora que fui  1569195706
            4  Buen lugar para escuchar buen rock. De domingo...  1566197539
mcCarthysEn 0  They need person to regulate the sound inside ...  1566612760
            1  One of the best pubs around.\nGreat service, g...  1518688093
            2  I love this place, one of the best places to d...  1522860496
            3  Rockers, music lovers in general will enjoy th...  1516852970
            4                 Great place to listen to good rock  1531876412

In [19]:
similarTrompos = gmaps.places_nearby(location='20.998842,-89.617407',radius=500, type='restaurant', rank_by='prominence')
similarTrompos=pd.read_json(json.dumps(similarTrompos['results']), orient='records') # Finding places similar to Los Trompos
similarTrompos.drop(["geometry", "icon","id", "opening_hours", "photos", "plus_code", "price_level","reference", "scope", "vicinity" ], axis=1, inplace=True)
similarTrompos
#'name', 'place_id', 'rating', 'types', 'user_ratings_total'

,name,place_id,rating,types,user_ratings_total
0,Los Trompos,ChIJpVKXOq12Vo8RK4bUWILT9dI,4.5,"[restaurant, food, point_of_interest, establis...",3116.0
1,Mi Viejo Molino,ChIJA2XvLq12Vo8RmHzVkbC-a1M,4.2,"[restaurant, food, point_of_interest, establis...",1383.0
2,Pizza del Perro Negro,ChIJS67Ey6x2Vo8RTiTblDl7VT0,4.4,"[restaurant, food, point_of_interest, establis...",1786.0
3,Mr. Pampas,ChIJE1CvhrJ2Vo8RF6OCmqVdXjU,4.6,"[restaurant, food, point_of_interest, establis...",3910.0
4,A la pimienta,ChIJ_7yIt7J2Vo8ROAqvR1B2Ivc,4.5,"[bar, restaurant, food, point_of_interest, est...",257.0
5,Los Originales Tacos de Res,ChIJScV8m1JxVo8RGtH_DNMAHcs,4.5,"[restaurant, food, point_of_interest, establis...",33.0
6,Osteria Piccoli,ChIJ8cAMZLJ2Vo8RzqIacVgeGAU,4.7,"[restaurant, food, point_of_interest, establis...",315.0
7,Burger King,ChIJY9x1Tq12Vo8RJcAtqpexutk,4.1,"[restaurant, food, point_of_interest, establis...",2368.0
8,Muelle 8,ChIJY7vsm8Z2Vo8RJI7plSxAcmc,4.5,"[restaurant, food, point_of_interest, establis...",196.0
9,McCarthy's,ChIJAQMIqrJ2Vo8RyNB-NE2HXFw,4.5,"[bar, restaurant, food, point_of_interest, est...",3147.0
10,Trotter's,ChIJgbGOKq12Vo8RqhK2SdKJzdQ,4.6,"[restaurant, food, point_of_interest, establis...",657.0
11,Mago's Restaurante,ChIJK3zxq3N3Vo8R2ggPcP6c71c,5.0,"[restaurant, food, point_of_interest, establis...",2.0
12,Little Caesars Pizza,ChIJF4Txyqx2Vo8RcCd1I-3_uDg,4.1,"[meal_takeaway, restaurant, food, point_of_int...",460.0
13,Wings Wagon,ChIJe2eMV01xVo8RrEnoQoPqBq0,NaN,"[restaurant, food, point_of_interest, establis...",NaN
14,Taqueria Los Tortuguitas,ChIJd08xvLJ2Vo8RiZjcLRcE3pg,NaN,"[restaurant, food, point_of_interest, establis...",NaN
15,Tacos Doña Chona,ChIJfSFOZBl3Vo8RMKSzmbuK8-0,NaN,"[restaurant, food, point_of_interest, establis...",NaN
16,Cocina Esquinita Buenavista,ChIJIdADAztxVo8RnW7LfxOznss,4.4,"[restaurant, food, point_of_interest, establis...",9.0
17,RIEH,ChIJe9SSha12Vo8R4duZuE3Cc5c,4.5,"[restaurant, food, point_of_interest, establis...",94.0
18,ChichenTitlan Kekas,ChIJBVLY48N3Vo8RxIiZooRahC8,NaN,"[restaurant, food, point_of_interest, establis...",NaN
19,Zhen Liying,ChIJq6qq-lJxVo8RaQ2CCowNCUk,3.5,"[restaurant, food, point_of_interest, establis...",4.0

G. Create a Github Project as a Tutorial about How to Use the Google API. Don't forget to include a section with the set of instructions to obtain the Google API Key. In this tutorial, compare the use of the Google Maps [Places API] (https://developers.google.com/places/web-service/intro) and the Python [GoogleMaps](https://github.com/googlemaps/google-maps-services-python) Library using this activity tasks as examples.

## Checklist

| Task | Points |
|:----:|:------:|
|   Class Participation  |   10   |
|   a  |   10   |
|   b  |   10   |
|   c  |   10   |
|   d  |   10   |
|   e  |   10   |
|   f  |   20   |
|   g  |   20   |


* **Important!** Partial credit can be obteined in each task.
* Don not forget to document your functions! [Here](http://google.github.io/styleguide/pyguide.html) is the Python Programming Styleguide from Google. [Section 3.8](http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) is about Comments and Docstrings.
* To obtain the Class Participation Score you must complete an early submission with tasks: A, B and C.